apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: danisosei20/quotes-back:v4.1
        name: back-api
        env:
          - name: SQLALCHEMY_DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: back-secret
                key: usernameandpassword
        ports:
        - containerPort: 3000
          name: http
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
  - name: http
    port: 3000
    targetPort: 3000

---
apiVersion: v1
kind: Secret
metadata:
  name: back-secret
type: Opaque
data:
  usernameandpassword: bXlzcWwrcHlteXNxbDovL3Jvb3Q6cm9vdEBkYXRhOjMzMDYvbXlkYXRhYmFzZQo=